### PR TITLE
Allow git dependencies not on master

### PR DESCRIPTION
**Pull request by lochsh**
cc @mbirtwell

### CODE REVIEW

**Review by mbirtwell — APPROVED** [review]
Looks good, I think I'd consider including the event name check too. But I don't know if that gains us anything.

**Comment by lochsh** [comment]
I have `==` instead of `!=` :scream:

**Comment by lochsh** [comment]
So I expected the reason this wasn't working for me in `trap-designs` was because we needed `insteadOf` for `git@github.com` not just `ssh://git@github.com`. And I was right, but my investigation was hindered by a few things, which I note here to help prevent future similar mistakes:

1. I didn't kill my ssh agent, so it looked like things were working with the PAT but in fact it was just using SSH. More verbosity options from git commands would have revealed this sooner.
2. I initially tried adding an `insteadOf` to the config for `git@github.com`, but I didn't put `:` at the end so it was not a valid url
3. I then added the `:` but was missing the `/` in the url it replaces

**Comment by mbirtwell** [comment]
Sorry should have paid more attention to this. I've tried this before and couldn't get it to work. The git config file is keyed on what you'd replacing with not what you're replacing. So what've you've done there is equivalent of trying to create a dictionary:
```
{
    "url."https://oxfordionics:${{ inputs.GHA_TOKEN }}@github.com".insteadOf": "ssh://git@github.com",
    "url."https://oxfordionics:${{ inputs.GHA_TOKEN }}@github.com/".insteadOf": "git@github.com",
}
```

Which is different to what I've tried before in that you've got an extra `/` in the second key. Where as in my case both my keys were the same, so this might actually work. It's also possible that this will canonicalize somewhere internally and so the new config would overwrite the old.

**Pull request merged**
